THEME_NAME: Headline
THEME_VERSION: 1.0.0
POSTS_PER_PAGINATION: 6

colors: 
  light: 
    accent_color: f51919
    primary_text_color: 15171a
    secondary_text_color: 999
  dark: 
    accent_color: f51919
    primary_text_color: f6f6f6
    secondary_text_color: 999

fonts: 
  body: 
    size: 1.6rem
    family: Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif
  heading: 
    family: Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif
  content: 
    family: Lora, Georgia, Times, serif
  code: 
    size: 15px 
    family: Menlo, Consolas, Monaco, Liberation Mono, Lucida Console, monospace; 

settings:
  home:
    tag_1:
      show: true
      slug: autem
    tag_2:
      show: true
      slug: deserunt
    tag_3:
      show: true
      slug: enim
    tag_4:
      show: true
      slug: laboriosam
    tag_5:
      show: true
      slug: nulla
    tag_6: 
      show: true
      slug: welcome
  loop:
    authors: true
    featured_image: true
  post:
    authors: true
    tags: true
    featured_image: true
  social: true
  feed: true
  copyright:
    show_hide: true
    copy_text: Headline © 2023. Powered by Hyvor